# Generated by Django 3.1.1 on 2020-10-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201028_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='list_name',
            field=models.CharField(default='Watchlist', max_length=15),
        ),
    ]
