# Generated by Django 3.1.1 on 2020-10-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201028_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(default=1),
        ),
    ]
