# Generated by Django 3.1.1 on 2020-10-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_starting_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='value',
            new_name='bid_value',
        ),
    ]
